/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.Image;
import java.util.Arrays;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author L-4 Sys 6
 */
public class click extends javax.swing.JFrame {
long t;
long d=90000;
ImageIcon ibg;
    /**
     * Creates new form click
     */
Integer a[]= new Integer[26];
    public click() {
        initComponents();
        
    l.setBounds(0,0,1366,768);
    Image bg=new ImageIcon("Images\\alphabg.png").getImage();
    Image nbg=bg.getScaledInstance(l.getWidth(), l.getHeight(), Image.SCALE_SMOOTH);
    ibg=new ImageIcon(nbg);
    l.setIcon(ibg);
    
    for(int n=0;n<26;n++)
    {
        a[n]=n;
    }
    Collections.shuffle(Arrays.asList(a));
    
    l1.setText(""+(char)('A'+a[0]));
    l2.setText(""+(char)('A'+a[1]));
    l3.setText(""+(char)('A'+a[2]));
    l4.setText(""+(char)('A'+a[3]));
    l5.setText(""+(char)('A'+a[4]));
    l6.setText(""+(char)('A'+a[5]));
    l7.setText(""+(char)('A'+a[6]));
    l8.setText(""+(char)('A'+a[7]));
    l9.setText(""+(char)('A'+a[8]));
    l10.setText(""+(char)('A'+a[9]));
}

    void diff(String a)
    {
        d=Integer.parseInt(a);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        l9 = new javax.swing.JLabel();
        l10 = new javax.swing.JLabel();
        l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Click");
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("jLabel1");
        l1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l1MouseClicked(evt);
            }
        });
        getContentPane().add(l1);
        l1.setBounds(30, 20, 25, 25);

        l2.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("jLabel2");
        l2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l2MouseClicked(evt);
            }
        });
        getContentPane().add(l2);
        l2.setBounds(90, 20, 25, 25);

        l3.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("jLabel3");
        l3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l3MouseClicked(evt);
            }
        });
        getContentPane().add(l3);
        l3.setBounds(160, 20, 25, 25);

        l4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("jLabel4");
        l4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l4MouseClicked(evt);
            }
        });
        getContentPane().add(l4);
        l4.setBounds(230, 20, 25, 25);

        l5.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("jLabel5");
        l5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l5MouseClicked(evt);
            }
        });
        getContentPane().add(l5);
        l5.setBounds(290, 20, 25, 25);

        l6.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("jLabel6");
        l6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l6MouseClicked(evt);
            }
        });
        getContentPane().add(l6);
        l6.setBounds(30, 60, 25, 25);

        l7.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l7.setText("jLabel7");
        l7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l7MouseClicked(evt);
            }
        });
        getContentPane().add(l7);
        l7.setBounds(90, 60, 25, 25);

        l8.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setText("jLabel8");
        l8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l8MouseClicked(evt);
            }
        });
        getContentPane().add(l8);
        l8.setBounds(160, 60, 25, 25);

        l9.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l9.setText("jLabel9");
        l9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l9MouseClicked(evt);
            }
        });
        getContentPane().add(l9);
        l9.setBounds(230, 60, 25, 25);

        l10.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l10.setText("jLabel10");
        l10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                l10MouseClicked(evt);
            }
        });
        getContentPane().add(l10);
        l10.setBounds(290, 60, 25, 25);
        getContentPane().add(l);
        l.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
    }//GEN-LAST:event_formMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
setExtendedState(this.MAXIMIZED_BOTH);
    JOptionPane.showMessageDialog(this, "Click them in anti-alphabetical order");
    {
        t=System.currentTimeMillis();
        l1.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l2.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l3.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l4.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l5.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l6.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l7.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l8.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l9.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
        l10.setBounds((int)(Math.random()*1325), (int)(Math.random()*725), 25 ,25);
    }
    }//GEN-LAST:event_formWindowOpened

    private void l1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l1MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l1.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l1.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l1.setVisible(false);
    l1.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l1MouseClicked

    private void l2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l2MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l2.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l2.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l2.setVisible(false);
    l2.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l2MouseClicked

    private void l3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l3MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l3.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l3.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l3.setVisible(false);
    l3.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l3MouseClicked

    private void l4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l4MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l4.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l4.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l4.setVisible(false);
    l4.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}     
    }//GEN-LAST:event_l4MouseClicked

    private void l5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l5MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l5.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l5.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l5.setVisible(false);
    l5.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l5MouseClicked

    private void l6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l6MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l6.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l6.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l6.setVisible(false);
    l6.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l6MouseClicked

    private void l7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l7MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l7.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l7.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l7.setVisible(false);
    l7.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l7MouseClicked

    private void l8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l8MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l8.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l8.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l8.setVisible(false);
    l8.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l8MouseClicked

    private void l9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l9MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l9.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)) &&
    (int)(l9.getText()).charAt(0)>=((int)(l10.getText()).charAt(0)))
{
    l9.setVisible(false);
    l9.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l9MouseClicked

    private void l10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_l10MouseClicked
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
if ((int)(l10.getText()).charAt(0)>=((int)(l2.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l3.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l4.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l5.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l6.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l7.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l8.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l9.getText()).charAt(0)) &&
    (int)(l10.getText()).charAt(0)>=((int)(l1.getText()).charAt(0)))
{
    l10.setVisible(false);
    l10.setText("@");
}
else
{
    JOptionPane.showMessageDialog(null, "WRONG CLICK!!!!!");
}
    }//GEN-LAST:event_l10MouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
long h=0;
if(System.currentTimeMillis()>=t+d)
{
    JOptionPane.showMessageDialog(rootPane, "TIME UP!!!");
    {
        this.dispose();
        new gamemenu().setVisible(true);
    }
}
else if ((l1.getText().equals("@")) && l2.getText().equals("@") && l3.getText().equals("@") && 
        l4.getText().equals("@") && l5.getText().equals("@") && l6.getText().equals("@") && 
        l7.getText().equals("@") && l8.getText().equals("@") && 
        l9.getText().equals("@") && l10.getText().equals("@"))
{
    h=(System.currentTimeMillis()-t)/1000;
    JOptionPane.showMessageDialog(null,"congo your time was = "+h+" seconds");
    {
        this.dispose();
        new gamemenu().setVisible(true);
    }
}
    }//GEN-LAST:event_formMouseMoved

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
l1.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l2.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l3.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l4.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l5.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l6.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l7.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l8.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l9.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));
l10.setLocation((int)(Math.random()*1325), (int)(Math.random()*725));        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(click.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(click.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(click.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(click.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new click().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l10;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    // End of variables declaration//GEN-END:variables
}
