/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author L-4 Sys 6
 */
public class race extends javax.swing.JFrame {
    
    /**
     * Creates new form race
     */
    ImageIcon ibg;
    public race() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        
        l.setBounds(0,0,1366,768);
        b2.setLocation(1307,27);
        
        l1.setLocation(0,100);
        l2.setLocation(0,200);
        l3.setLocation(0,300);
        l4.setLocation(0,400);
        l5.setLocation(0,500);
    
    Image bg=new ImageIcon("Images\\hbg.jpg").getImage();
    Image nbg=bg.getScaledInstance(l.getWidth(), l.getHeight(), Image.SCALE_SMOOTH);
    ibg=new ImageIcon(nbg);
    
    l.setIcon(ibg);
    l1.setIcon(new ImageIcon("Images\\h1.png"));
    l2.setIcon(new ImageIcon("Images\\h2.png"));
    l3.setIcon(new ImageIcon("Images\\h3.png"));
    l4.setIcon(new ImageIcon("Images\\h4.png"));
    l5.setIcon(new ImageIcon("Images\\h5.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        l3 = new javax.swing.JLabel();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        l = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Horse Race");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        l1.setText("1");
        getContentPane().add(l1);
        l1.setBounds(60, 110, 70, 30);

        l2.setText("2");
        getContentPane().add(l2);
        l2.setBounds(160, 130, 70, 30);

        b1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        b1.setText("GO");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(0, 30, 160, 70);

        l3.setText("3");
        getContentPane().add(l3);
        l3.setBounds(190, 180, 70, 30);

        l4.setText("4");
        getContentPane().add(l4);
        l4.setBounds(160, 220, 70, 30);

        l5.setText("5");
        getContentPane().add(l5);
        l5.setBounds(210, 280, 70, 30);

        b2.setText("Exit");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(321, 0, 60, 80);
        getContentPane().add(l);
        l.setBounds(10, 240, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
l1.setLocation(l1.getX()+(int)(Math.random()*((50-0)+0)),100);
l2.setLocation(l2.getX()+(int)(Math.random()*((50-0)+0)),200);
l3.setLocation(l3.getX()+(int)(Math.random()*((50-0)+0)),300);
l4.setLocation(l4.getX()+(int)(Math.random()*((50-0)+0)),400);
l5.setLocation(l5.getX()+(int)(Math.random()*((50-0)+0)),500);
if(l1.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "1 Wins");
    {
        l1.setLocation(0,100);
        l2.setLocation(0,200);
        l3.setLocation(0,300);
        l4.setLocation(0,400);
        l5.setLocation(0,500);
    }
}
else if(l2.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "2 Wins");
    {
        l1.setLocation(0,100);
        l2.setLocation(0,200);
        l3.setLocation(0,300);
        l4.setLocation(0,400);
        l5.setLocation(0,500);
    }
}
else if(l3.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "3 Wins");
    {
        l1.setLocation(0,100);
        l2.setLocation(0,200);
        l3.setLocation(0,300);
        l4.setLocation(0,400);
        l5.setLocation(0,500);
    }
}
else if(l4.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "4 Wins");
    {
        l1.setLocation(0,100);
        l2.setLocation(0,200);
        l3.setLocation(0,300);
        l4.setLocation(0,400);
        l5.setLocation(0,500);
    }
}
else if(l5.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "5 Wins");
    {
        l1.setLocation(0,100);
        l2.setLocation(0,200);
        l3.setLocation(0,300);
        l4.setLocation(0,400);
        l5.setLocation(0,500);
    }
}
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
l1.setLocation(l1.getX()+(int)(Math.random()*((50-0)+0)),100);
l2.setLocation(l2.getX()+(int)(Math.random()*((50-0)+0)),200);
l3.setLocation(l3.getX()+(int)(Math.random()*((50-0)+0)),300);
l4.setLocation(l4.getX()+(int)(Math.random()*((50-0)+0)),400);
l5.setLocation(l5.getX()+(int)(Math.random()*((50-0)+0)),500);
if(l1.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "1 Wins");
}
else if(l2.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "2 Wins");
}
else if(l3.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "3 Wins");
}
else if(l4.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "4 Wins");
}
else if(l5.getX()>1300)
{
    JOptionPane.showMessageDialog(null, "5 Wins");
}        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(race.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new race().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    // End of variables declaration//GEN-END:variables
}
